---
server:
  httpPort: 8080
  serverUrl: http://localhost:8080/
  maxThreads: 512
  minThreads: 128
  httpConfiguration:
    sendServerVersion: false
dataSources:
  - jndiName: datasources/ExampleDS
    jdbcUrl: jdbc:h2:~/exemplo.db;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    maxPoolSize: 20
    minPoolSize: 1
    connectionTestQuery: SELECT 1
    connectionTimeout: 30000
    maxIdleTime: 120000
